In [19]:
 #Part 1: Proposal - Academic Stress levels

In [20]:
import pandas as pd
stress_level = '/Users/daniellamori/Desktop/Proyecto USF/Academic-stress-levels-/academic Stress level - maintainance 1 2.csv'
df = pd.read_csv(stress_level)

In [21]:
df.head()

,Timestamp,Your Academic Stage,Peer pressure,Academic pressure from your home,Study Environment,What coping strategy you use as a student?,"Do you have any bad habits like smoking, drinking on a daily basis?",What would you rate the academic competition in your student life,Rate your academic stress index
0,24/07/2025 22:05:39,undergraduate,4,5,Noisy,Analyze the situation and handle it with intel...,No,3,5
1,24/07/2025 22:05:52,undergraduate,3,4,Peaceful,Analyze the situation and handle it with intel...,No,3,3
2,24/07/2025 22:06:39,undergraduate,1,1,Peaceful,"Social support (friends, family)",No,2,4
3,24/07/2025 22:06:45,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,4,3
4,24/07/2025 22:08:06,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,4,5

In [22]:
print(df.columns.tolist())
#total of 
#What again does non-null count mean?

['Timestamp', 'Your Academic Stage', 'Peer pressure', 'Academic pressure from your home', 'Study Environment', 'What coping strategy you use as a student?', 'Do you have any bad habits like smoking, drinking on a daily basis?', 'What would you rate the academic  competition in your student life', 'Rate your academic stress index ']

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 9 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Timestamp                                                            140 non-null    str
 1   Your Academic Stage                                                  140 non-null    str
 2   Peer pressure                                                        140 non-null    int64
 3   Academic pressure from your home                                     140 non-null    int64
 4   Study Environment                                                    139 non-null    str
 5   What coping strategy you use as a student?                           140 non-null    str
 6   Do you have any bad habits like smoking, drinking on a daily basis?  140 non-null    str
 7   What would you rate the academic  competition in your student life   140 non-null    int64
 8   Rate your academic stress index                                      140 non-null    int64
dtypes: int64(4), str(5)
memory usage: 21.7 KB

In [24]:
df.describe()

,Peer pressure,Academic pressure from your home,What would you rate the academic competition in your student life,Rate your academic stress index
count,140.000000,140.000000,140.000000,140.000000
mean,3.071429,3.178571,3.492857,3.721429
std,1.083844,1.276618,1.028349,1.032339
min,1.000000,1.000000,1.000000,1.000000
25%,2.000000,2.000000,3.000000,3.000000
50%,3.000000,3.000000,4.000000,4.000000
75%,4.000000,4.000000,4.000000,4.000000
max,5.000000,5.000000,5.000000,5.000000